package me.timecutstr.mcsiege.manager;

public enum GameState {
    SETUP, LOBBY, SHOP, VOTING, STARTING, WAVE1, WAVE2, WAVE3, WAVE4, WAVE5, WAVE6, WAVE7, WAVESPECIAL1, WAVESPECIAL2, WON, LOOSE, RESTARTING, BOSS;
}

