package me.timecutstr.mcsiege.manager;

public enum GameState {
    SETUP, LOBBY, SHOP, STARTING, LEVEL1, LEVEL2, LEVEL3, LEVEL4, LEVEL5, LEVEL6, LEVEL7, WAVESPECIAL1, WAVESPECIAL2, WON, LOOSE, BOSS;
}

