targetLocation:
  ==: org.bukkit.Location
  world: minesiege
  x: 43.69999998807907
  y: -60.0625
  z: 165.60282931229648
  pitch: 76.34994
  yaw: 2.2560656

spawnLocation1:
  ==: org.bukkit.Location
  world: minesiege
  x: -23.941458659410397
  y: -60.0
  z: 165.53173242770683
  pitch: 16.649984
  yaw: -88.793335

spawnLocation2:
  ==: org.bukkit.Location
  world: minesiege
  x: 42.558939100485254
  y: -60.0
  z: 103.44090144397943
  pitch: 12.74998
  yaw: -0.14343262

spawnLocation3:
  ==: org.bukkit.Location
  world: minesiege
  x: 54.13411446602575
  y: -60.0
  z: 234.07406943491944
  pitch: 29.099949
  yaw: -176.5445

spawnLocation4:
  ==: org.bukkit.Location
  world: minesiege
  x: 96.72024584935068
  y: -60.0
  z: 165.74642971946668
  pitch: 7.049968
  yaw: 86.70648

SpawnJoueurLocation:
  ==: org.bukkit.Location
  world: minesiege
  x: 43.72024584935068
  y: -56.0
  z: 165.74642971946668
  pitch: 7.049968
  yaw: 86.70648

WeaponShopLocation:
  ==: org.bukkit.Location
  world: minesiege
  x: 38.139352285358484
  y: -60.0
  z: 170.69999998807907
  pitch: 17.699951
  yaw: 176.98541

ArmorShopLocation:
  ==: org.bukkit.Location
  world: minesiege
  x: 37.70339422931514
  y: -60.0
  z: 159.42541493356353
  pitch: 3.2998495
  yaw: -4.965576

RevendeurShopLocation:
  ==: org.bukkit.Location
  world: minesiege
  x: 49.984
  y: -60.0
  z: 170.579
  pitch: 3.2998495
  yaw: -4.965576

prix:
  IRON_SWORD : 20
  DIAMOND_SWORD : 25
  NETHERITE_SWORD : 30
  BOW : 5
  ARROW : 5
  SHIELD : 10
  EGG : 20
  LEATHER_HELMET : 1
  LEATHER_CHESTPLATE : 1
  LEATHER_LEGGINGS : 1
  LEATHER_BOOTS : 1
  IRON_HELMET : 5
  IRON_CHESTPLATE : 5
  IRON_LEGGINGS : 5
  IRON_BOOTS : 5
  DIAMOND_HELMET : 10
  DIAMOND_CHESTPLATE : 10
  DIAMOND_LEGGINGS : 10
  DIAMOND_BOOTS : 10
  NETHERITE_HELMET : 15
  NETHERITE_CHESTPLATE : 15
  NETHERITE_LEGGINGS : 15
  NETHERITE_BOOTS : 15
  GOLDEN_APPLE : 5


PrixEnchantement : 10
PrixEnchantementFlamme : 20
PrixEnchantementInfinity : 15
PrixEnchantementKnockBack : 10
PrixEnchantementThorn : 15

openWaves : 4

orDeDépart : 40

ViesMax : 20

JoueurMax : 5

RécompenseFinDeNiveau : 20

RespawnTime : 5

World : minesiege