name: McSiege
version: '${project.version}'
main: me.timecutstr.mcsiege.McSiege
api-version: 1.19
authors: [ TimeCutStr ]
description: un plugin de mini jeux où les joueurs se font attaquer par des hordes de monstres
website: https://linktr.ee/timecut
commands:
  spawn:
    description: fait spawn un zombie
    usage: /<command>

  spawnTarget:
    description: fait spawn le villageois victime
    usage: /<command>

  setTarget:
    description: set la location du joueur comme position de la victime
    usage: /<command>

  resetTarget:
    description: reset la cible des zombies

  clear:
    description: Tue tous les monstres du niveau ainsi que la target

  setup:
    description: Passe en setup pour mettre en place les spawns des monstres et le centre de la map

  setSpawn:
    description: Permet de définir le point de spawn des monstres mais uniquement en phase de SetUp.

  start:
    description: Lance la partie si on se trouve dans le lobby

  menu:
    description: Ouvre un menu

  setWeaponShop:
    description: Inscrit la position du weapon Shop dans le Config.yml

  setArmorShop:
    description: Inscrit la position de l'armor Shop dans le Config.yml

  lobby:
    description: Retourn au lobby et clear le niveau

  rdy:
    description: Inscrit le joueur dans le jeu
    aliases: ready

  reloadConfig:
    description: Prend en compte les modifications faites au config.yml

